# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c8dd45dcdf24f3f2ea940ff5dd382558a3f057041f801c38cd4e71f71ffb78570856646ae44e19380994988f1cb5ae116d66d838aa02a334ac9fbf01f0e3e88

test:
  secret_key_base: d055363896bbed735cd51d2bfb6e9d3abdb61cd417d4eb1670b69267fd68d5a2c1f50c5c86714b052159df24be8d12f53af4e159150da6522ac313d460d182af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
